language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly
  - hhvm
  - hhvm-nightly

matrix:
  fast_finish: true
  allow_failures:
    - php
        - 7.1
        - nightly
        - hhvm-nightly
# faster builds on new travis containers
sudo: false

script:
  - php testsuite.php --ci

after_script:
  - travis_retry wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
